// <auto-generated />
using System;
using Basket.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basket.API.Infrastructure.BasketMigrations
{
    [DbContext(typeof(BasketContext))]
    [Migration("20231012220439_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroceriesStore.Services.Basket.API.Model.BasketItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerBasketId")
                        .HasColumnType("int");

                    b.Property<decimal>("OldUnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("CustomerBasketId");

                    b.ToTable("BasketItem", (string)null);
                });

            modelBuilder.Entity("GroceriesStore.Services.Basket.API.Model.CustomerBasket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BuyerId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("GroceriesStore.Services.Basket.API.Model.BasketItem", b =>
                {
                    b.HasOne("GroceriesStore.Services.Basket.API.Model.CustomerBasket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroceriesStore.Services.Basket.API.Model.CustomerBasket", null)
                        .WithMany("Items")
                        .HasForeignKey("CustomerBasketId");

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("GroceriesStore.Services.Basket.API.Model.CustomerBasket", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
