version: '3.4'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The ESHOP_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     ESHOP_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file
# An external IP or DNS name has to be used (instead localhost and the 10.0.75.1 IP) when testing the Web apps and the Xamarin apps from remote machines/devices using the same WiFi, for instance.

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - eshop-sqldata:/var/opt/mssql

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__IdentityDb=${ESHOP_AZURE_IDENTITY_DB:-Server=sqldata;Database=GroceriesStore.Services.IdentityDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true}
      - MvcClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:7100
      - BasketApiClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:7103
      - WebShoppingAggClient=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:7121
    ports:
      - "7105:80"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__BasketDb=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=GroceriesStore.Services.BasketDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true}
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - Identity__Url=http://identity-api
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:7105
      - UseLoadTest=${USE_LOADTEST:-False}
      - PATH_BASE=/basket-api
    ports:
      - "7103:80"
      - "9103:81"

  basket-api2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__BasketDb=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=GroceriesStore.Services.BasketDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true}
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - Identity__Url=http://identity-api
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:7105
      - UseLoadTest=${USE_LOADTEST:-False}
      - PATH_BASE=/basket-api2
    ports:
      - "7113:80"
      - "9113:81"

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__CatalogDb=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=GroceriesStore.Services.CatalogDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true}
      - PicBaseUrl=${ESHOP_STORAGE_CATALOG_URL}
      - PATH_BASE=/catalog-api
    ports:
      - "7101:80"
      - "9101:81"

  catalog-api2:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - ConnectionStrings__CatalogDb=${ESHOP_AZURE_CATALOG_DB:-Server=sqldata;Database=GroceriesStore.Services.CatalogDb;User Id=sa;Password=Pass@word;Encrypt=False;TrustServerCertificate=true}
      - PicBaseUrl=${ESHOP_STORAGE_CATALOG_URL}
      - PATH_BASE=/catalog-api2
    ports:
      - "7111:80"
      - "9111:81"


  webshoppingagg:
    environment:
      - urls__basket=http://basket-api
      - urls__catalog=http://catalog-api
      - urls__orders=http://ordering-api
      - urls__identity=http://identity-api
      - urls__grpcBasket=http://basket-api:81
      - urls__grpcCatalog=http://catalog-api:81
      - urls__grpcOrdering=http://ordering-api:81
      - ReverseProxy__Clusters__basket__Destinations__destination0__Address=http://basket-api
      - ReverseProxy__Clusters__catalog__Destinations__destination0__Address=http://catalog-api
      - CatalogUrlHC=http://catalog-api/hc
      - IdentityUrlHC=http://identity-api/hc
      - BasketUrlHC=http://basket-api/hc
      - Identity__Url=http://identity-api
      - Identity__ExternalUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:7105
    ports:
      - "7151:5000"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - PurchaseUrl=http://webshoppingagg:5000
      - IdentityUrl=http://${ESHOP_EXTERNAL_DNS_NAME_OR_IP}:7105
      - IdentityUrlHC=http://identity-api/hc
      - UseLoadTest=${USE_LOADTEST:-False}
    ports:
      - "7100:80"

volumes:
  eshop-sqldata:
    external: false
